<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class FarmerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('farmers')->insert([
            [
                'name' => 'Maria Santos',
                'email' => 'maria.santos@example.com',
                'phone' => '+63 917 123 4567',
                'bio' => 'Organic vegetable farmer with 5 years experience. Looking to share cold storage costs with other farmers.',
                'location' => 'Laguna, Philippines',
                'latitude' => 14.2683,
                'longitude' => 121.2413,
                'profile_image' => '/placeholder-user.jpg',
                'produce_types' => json_encode(['Tomatoes', 'Lettuce', 'Bell Peppers', 'Cabbage']),
                'storage_capacity_needed' => 10,
                'max_temperature' => 4.0,
                'min_temperature' => 2.0,
                'is_looking_for_storage' => true,
                'has_excess_storage' => false,
                'cost_per_cubic_meter' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Juan Dela Cruz',
                'email' => 'juan.delacruz@example.com',
                'phone' => '+63 918 234 5678',
                'bio' => 'Fruit farmer specializing in mangoes and bananas. Has excess cold storage space available for sharing.',
                'location' => 'Cavite, Philippines',
                'latitude' => 14.4791,
                'longitude' => 120.8970,
                'profile_image' => '/placeholder-user.jpg',
                'produce_types' => json_encode(['Mangoes', 'Bananas', 'Papayas', 'Pineapples']),
                'storage_capacity_needed' => null,
                'max_temperature' => 5.0,
                'min_temperature' => 3.0,
                'is_looking_for_storage' => false,
                'has_excess_storage' => true,
                'cost_per_cubic_meter' => 50.00,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ana Rodriguez',
                'email' => 'ana.rodriguez@example.com',
                'phone' => '+63 919 345 6789',
                'bio' => 'Dairy farmer with excess cold storage. Looking to help other farmers reduce costs through shared storage.',
                'location' => 'Batangas, Philippines',
                'latitude' => 13.7565,
                'longitude' => 121.0583,
                'profile_image' => '/placeholder-user.jpg',
                'produce_types' => json_encode(['Dairy Products', 'Cheese', 'Yogurt', 'Milk']),
                'storage_capacity_needed' => null,
                'max_temperature' => 4.5,
                'min_temperature' => 2.5,
                'is_looking_for_storage' => false,
                'has_excess_storage' => true,
                'cost_per_cubic_meter' => 45.00,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Carlos Mendoza',
                'email' => 'carlos.mendoza@example.com',
                'phone' => '+63 920 456 7890',
                'bio' => 'Vegetable farmer growing organic produce. Seeking storage partnerships to reduce costs.',
                'location' => 'Quezon, Philippines',
                'latitude' => 14.5400,
                'longitude' => 121.5000,
                'profile_image' => '/placeholder-user.jpg',
                'produce_types' => json_encode(['Carrots', 'Broccoli', 'Cauliflower', 'Spinach']),
                'storage_capacity_needed' => 8,
                'max_temperature' => 3.5,
                'min_temperature' => 1.5,
                'is_looking_for_storage' => true,
                'has_excess_storage' => false,
                'cost_per_cubic_meter' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Elena Garcia',
                'email' => 'elena.garcia@example.com',
                'phone' => '+63 921 567 8901',
                'bio' => 'Herb and spice farmer with modern cold storage facilities. Open to sharing space with compatible farmers.',
                'location' => 'Rizal, Philippines',
                'latitude' => 14.5667,
                'longitude' => 121.2000,
                'profile_image' => '/placeholder-user.jpg',
                'produce_types' => json_encode(['Basil', 'Oregano', 'Thyme', 'Rosemary']),
                'storage_capacity_needed' => null,
                'max_temperature' => 4.0,
                'min_temperature' => 2.0,
                'is_looking_for_storage' => false,
                'has_excess_storage' => true,
                'cost_per_cubic_meter' => 55.00,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Michael Torres',
                'email' => 'michael.torres@example.com',
                'phone' => '+63 922 678 9012',
                'bio' => 'Mixed crop farmer looking for storage partners. Specializes in seasonal vegetables and fruits.',
                'location' => 'Bulacan, Philippines',
                'latitude' => 14.7944,
                'longitude' => 120.8792,
                'profile_image' => '/placeholder-user.jpg',
                'produce_types' => json_encode(['Eggplant', 'Okra', 'Squash', 'Watermelon']),
                'storage_capacity_needed' => 12,
                'max_temperature' => 5.0,
                'min_temperature' => 3.0,
                'is_looking_for_storage' => true,
                'has_excess_storage' => false,
                'cost_per_cubic_meter' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
